eureka: 
  client: 
    register-with-eureka: true
    fetch-registry: true
    serviceUrl: 
      defaultZone: http://localhost:8761/eureka/
  instance: 
    hostname: localhost

data:
  branch: develop
  enabled: true
  
spring: 
  cloud: 
    gateway: 
      routes:
      - id: MOVIE-SEAT-AVAILABILITY
        uri: lb://MOVIE-SEAT-AVAILABILITY
        predicates:
        - Path=/cinemax/avail/**
      - id: MOVIE-SEAT-BOOKING
        uri: lb://MOVIE-SEAT-BOOKING
        predicates:
        - Path=/cinemax/book/**
